### ISSUE TITLE
Issues with Latex Rendering

### ISSUE THREAD

**Issue by saadtony** [saadgroup/PyModPDE#22] opened 2020-11-10 21:40 UTC
Sometimes strange looking modified equations show up with terms that do not multiply a derivative.
This is an example from James.
`from sympy import symbols,latex
from src.pymodpde import DifferentialEquation, i, n

u= symbols('u')
D= symbols('D') 
 
pde = DifferentialEquation( dependentVarName='y',
                            independentVarsNames=['x'])

t = n+1
advection = ( pde.y(time=t,x=i) - pde.y(time=t,x=i-1) ) / (pde.dx)
diffusion = ( pde.y(time=t,x=i-1)
             - 2*pde.y(time=t,x=i)
             + pde.y(time=t,x=i+1)
            ) / pde.dx**2

pde.set_rhs( (-u*advection) + (D*diffusion ))

pde.generate_amp_factor()
pde.display_amp_factor()
pde.generate_modified_equation(nterms=3)
pde.display_modified_equation()`
One potential solution is to use `symbolic_modified_equation()` instead of `display_modified_equation` until the latter is fixed

**Comment by jcsutherland** [comment] 2020-11-10 22:11
Duplicate of #23

**Closed as completed** 2022-02-05 23:55 UTC
